name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: oven-sh/setup-bun@v2

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .nuxt
          key: ${{ runner.os }}-nuxt-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-nuxt-

      - run: bun install
      - run: bun run test

      - name: Static HTML export with Nuxt
        run: bun run generate
        env:
          PUBLIC_GOOGLE_SITE_VERIFICATION: ${{ vars.PUBLIC_GOOGLE_SITE_VERIFICATION }}
          PUBLIC_BING_SITE_VERIFICATION: ${{ vars.PUBLIC_BING_SITE_VERIFICATION }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # link to ./.output/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate repo
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
