name: Build (npm)

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .nuxt
          key: ${{ runner.os }}-nuxt-${{ hashFiles('package-lock.json', 'bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-nuxt-

      - run: npm ci

      - name: Prepare Nuxt
        run: npx nuxt prepare

      - name: Static HTML export with Nuxt
        run: npm run generate
        env:
          NUXT_PUBLIC_GOOGLE_SITE_VERIFICATION: ${{ vars.NUXT_PUBLIC_GOOGLE_SITE_VERIFICATION }}
          NUXT_PUBLIC_BING_SITE_VERIFICATION: ${{ vars.NUXT_PUBLIC_BING_SITE_VERIFICATION }}

      - name: Upload artifact
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}
